### ISSUE TITLE
2019年mLNHIICC_Setup.Ubuntu.zip解出來的檔名有變更了呦

### ISSUE THREAD

**Issue by ikaritw** [chihchun/personal-income-tax-docker#4]
mLNHIICC_Setup.Ubuntu.zip -> mLNHIICC_Setup.Ubuntu16.tar.gz
這個檔案已改名為 mLNHIICC_Setup.tar.gz 了

**Comment by peter279k** [comment]
This issue I have resolved on this [repository](https://github.com/peter279k/emask-tax-docker).

Please feel free to use this if this repository has not resolved :).

**Comment by chihchun** [comment]
Fixed in  https://github.com/chihchun/personal-income-tax-docker/commit/b89f68208eaad93859341f8eeae5e803957a71fa
